# Generated by Django 4.0.5 on 2022-06-30 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_value', to='product.product'),
        ),
    ]
