version: '3.8'

services:

  pgdb:
    image: postgres:14.1-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: torobche
      POSTGRES_PASSWORD: t0r0bch3
    volumes:
      - "db:/var/lib/postgresql/data_torobche"
    ports:
      - "8585:5432"
    expose:
      - "8585"

volumes:
  db:
    driver: local